import random

class MarketingAgent:
    def __init__(self, db):
        self.db = db

    def promote_latest_release(self):
        if not self.db.state["catalog"]:
            return
            
        latest_track = self.db.state["catalog"][-1]
        platforms = ["Twitter", "Instagram", "Spotify Editorial", "TikTok"]
        platform = random.choice(platforms)
        
        teaser_text = f"🔥 New Release: {latest_track['title']}! A unique {latest_track['genre']} experience generated by AI. #MusicGen #AI"
        
        promo_event = {
            "track_id": latest_track["id"],
            "platform": platform,
            "copy": teaser_text,
            "timestamp": self.db.state["simulated_date"]
        }
        
        self.db.state["marketing_log"].append(promo_event)
        self.db.save()
        self.db.log_event("marketing_log", f"Promoted {latest_track['id']} on {platform}")
