import random
import datetime
from .agent_base import AgentBase

class MarketingAgent(AgentBase):
    def __init__(self):
        super().__init__("Marketing Agent")
        
    def run_campaign(self):
        state = self.load_state()
        if not state["catalog"]:
            return

        # Pick a random recent track
        track = random.choice(state["catalog"][-5:])
        platforms = ["TikTok", "Twitter", "Instagram", "Spotify Editorial"]
        platform = random.choice(platforms)
        
        copy_text = ""
        if platform == "TikTok":
            copy_text = f"🔥 New Release: {track['title']}! A unique {track['genre']} experience generated by AI. #MusicGen #AI"
        elif platform == "Twitter":
            copy_text = f"Just dropped: {track['title']} ({track['tempo']} BPM). Generated via {track.get('music_model', 'Suno')}. Listen now! 🎵"
        else:
            copy_text = f"Now Streaming: {track['title']}. Vibes: {track['context']}. #NewMusic"

        # Log Campaign
        log_entry = {
            "track_id": track['id'],
            "platform": platform,
            "copy": copy_text,
            "timestamp": datetime.datetime.now().isoformat()
        }
        
        if "marketing_log" not in state: state["marketing_log"] = []
        state["marketing_log"].append(log_entry)
        
        # Add basic feed log
        feed_log = {
            "timestamp": datetime.datetime.now().isoformat(),
            "message": f"Promoted {track['id']} on {platform}"
        }
        state["marketing_log"].append(feed_log) # Using same array for simplicity or could be separate

        self.save_state(state)
        self.log(f"Campaign run for {track['title']} on {platform}")
